### ISSUE TITLE
Lightpad opens in the wrong monitor (using multiple displays)

### ISSUE THREAD

**Issue by fzamperin** [libredeb/lightpad#26]
Hello, I've installed lightpad today and it's awesome, the only thing i didn't find to configure is to choose a display to open, right now I have two monitors and lightpad opens in the wrong one, is there a way to configure this? Thanks a lot.

**Comment by flamesquirrel** [comment]
I have the same issue.

When using multiple displays on Ubuntu Budgie 21.10, the Lightpad Applet always and only displays on the left most display in the array. The expected behavior is that the applet opens on the display set as the primary display. The main issue with this, other than it not appearing where expected, is when the primary display's resolution is greater than that of the left most display. The result is that some of the icons then appear off-screen, as does the search bar and navigation strip.

The ideal solution would be for the panel to appear on the primary display at the correct resolution while extending the 'veil' to any other displays in the array. It would also be nice if clicking anywhere on the 'veil' would close the applet - much like a modal window functions in a web browser.

**Comment by libredeb** [comment]
Ok, thank you guys for the feedback... I recently obtained a new monitor. I'll try to reproduce this behavior to fix it. This issue can be resolved soon. Regards!
